spring:
  application:
    name: coupon
  datasource:
    url: jdbc:mariadb://localhost:3306/coupon
    username: user
    password: user
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-active: 8   # ?? ??? ?
          max-idle: 8     # ?? ?? ??? ?
          min-idle: 0     # ?? ?? ??? ?
