spring:
  application:
    name: batch
  datasource:
    url: jdbc:mariadb://localhost:3306/batch
    username: user
    password: user
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.haeun.batch