spring:
  application:
    name: petstats
  datasource:
    url: jdbc:mariadb://localhost:3306/pet_stats
    username: user
    password: user
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true